AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'lib/generators/snapshotable/templates/*'
    - 'spec/dummy/db/schema.rb'
    - 'vendor/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false