language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.4

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install: gem install bundler -v 1.17.3
before_script: ./scripts/prepare-db.sh
after_script: ./scripts/clean-db.sh